### PR TITLE
181 update error access level

### LINKED ISSUE #23: Add Information to README about CRUD operations
Add information to the README for getting started and using the CRUD operations.

### LINKED ISSUE #181: Operation.Error visibility
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

## Bug Description

Operation.Error enum types are not visible outside package. This way I cannot catch specific errors, but only generic errors which gives a generic message: "The operation couldn’t be completed. (SwiftCloudant.Operation.Error error 1.)"

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

From the example:
// Create a document
let create = PutDocumentOperation(id: "doc1", body: ["hello":"world"], databaseName: dbName) {(response, httpInfo, error) in
    if let error = error {
        print("Encountered an error while creating a document. Error:\(error)")
    } else {
        print("Created document \(response?["id"]) with revision id \(response?["rev"])")
    }
}
client.add(operation:create)

### 2. What you expected to happen

// Create a document
let create = PutDocumentOperation(id: "doc1", body: ["hello":"world"], databaseName: dbName) {(response, httpInfo, error) in
    if let error = error {
        switch error {
       case let opError as Operation.Error.http:
           print("http error occurred: \(opError.statusCode):   \(opError.response)
       default:
           print("Encountered an error while creating a document. Error:\(error)")
       }
    } else {
        print("Created document \(response?["id"]) with revision id \(response?["rev"])")
    }
}
client.add(operation:create)

### 3. What actually happened
   Code from 2 does not compile due to visibility of Operation.Error:
"'Error' is inaccessible due to 'internal' protection level"

## Environment details
OSX Mojave, Swift 4.2

### PR DESCRIPTION
**Pull request by emlaver**
## Checklist

- [x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](../blob/master/DCO1.1.txt)
- [ ] Added tests for code changes _or_ test/build only changes
- [x] Updated the change log file (`CHANGES.md`|`CHANGELOG.md`) _or_ test/build only changes
- [x] Completed the PR template below:

## Description
Updated Error to public access level to be visible outside of package
Fixes #181 

## Approach
Added `public` to `Operation.Error`

## Schema & API Changes
Changed visibility of `Operation.Error` to public

## Security and Privacy
"No change"

## Testing
Tested new change in separate swift project with code:
```
import SwiftCloudant
import Foundation
import CoreFoundation

let task = Process()
var environment =  ProcessInfo.processInfo.environment
let url = URL(string: environment["SERVER_URL"]!)!
let username = environment["SERVER_USER"]!
let password = environment["SERVER_PASSWORD"]!
let client = CouchDBClient(url: url, username: nil, password: nil)
let dbName = "swift"
let create = PutDocumentOperation(id: "swift", body: ["hello":"world"], databaseName: dbName) {(response, httpInfo, error) in
    if let error = error as? SwiftCloudant.Operation.Error {
        switch error {
        case .http(let httpError):
            print("http error status code: \(httpError.statusCode)  response: \(httpError.response)")
        default:
            print("Encountered an error while creating a document. Error:\(error)")
        }
    } else {
    print("Created document")
    let id = response?["id"]
    let rev = response?["rev"]
    print(id!)
    print(rev!)
  }
}
client.add(operation:create).waitUntilFinished()
```

## Monitoring and Logging
"No change"

### CODE REVIEW

File: Source/SwiftCloudant/Operations/Operation.swift [hunk 1]
```diff
@@ -25,7 +25,7 @@ public class Operation: Foundation.Operation, HTTPRequestOperation
     /**
      A enum of errors which could be returned.
      */
-    enum Error: Swift.Error {
+    public enum Error: Swift.Error {
```
Comment (ricellis) [inline Source/SwiftCloudant/Operations/Operation.swift]: This file will need a copyright update before merging though.
